### ISSUE TITLE
Could not find compiler executable css.exe

### ISSUE THREAD

**Issue by kk159963** [De-eloper/RunPE-Binder-Crypter#1]
Could not find compiler executable css.exe
![Uploading 螢幕擷取畫面 2022-10-10 185720.png…]()

**Comment by De-eloper** [comment]
not sure why this error happens and screenshot image is not loading for me right now. but the crypter uses .net v3.5 for compiling with codedom. try check in windows folder for C:\Windows\Microsoft.NET\ for Framework/Framework64 and if you dont have v3.5 folder you might need install .net framework 3.5 runtime at https://www.microsoft.com/en-us/download/details.aspx?id=25150. or maybe i think can be if you have another compiler for other programs. let me know

**Comment by De-eloper** [comment]
Sorry for late reply or I couldnt solve the issue. But if you are on Windows 10/11 I might figure the issue is .NET 2.0/3.5 is not enabled.

Check this article: https://www.groovypost.com/howto/enable-net-framework-2-0-and-3-5-windows-11/

Any other issue open a new one, if you still want to use this tool. Though it's outdated for now.
